### PR TITLE
fix: make lock-on client-sided

### LINKED ISSUE #157: Make lock-on client sided.
While the target is moving fast, server and client disagree where the target is and you have to aim ahead of your target to lock on. This get worse with ping.

### PR DESCRIPTION
**Pull request by allvei**
closes #157

### CODE REVIEW

File: src/game/shared/tf/passtime_convars.cpp [hunk 1]
```diff
@@ -12,81 +12,82 @@
 
 #define PASSTIME_CONVAR(NAME, STR, DESC) ConVar NAME(#NAME, #STR, FLAGS_DEFAULT, DESC)
 
-PASSTIME_CONVAR( tf_passtime_scores_per_round, 5, "Number of scores it takes to win a round. Similar to tf_flag_caps_per_round." );
```
Comment (drunderscore) [inline src/game/shared/tf/passtime_convars.cpp]: One day I feel we ought to clang-format the world to avoid these kinds of diffs from sneaking in. (no action needed)

File: src/game/shared/tf/passtime_convars.h [hunk 2]
```diff
@@ -31,6 +31,7 @@ extern ConVar
 	tf_passtime_flinch_boost,
 	tf_passtime_mode_homing_lock_sec,
 	tf_passtime_mode_homing_speed,
+	tf_passtime_lock_angle,
```
Comment (drunderscore) [inline src/game/shared/tf/passtime_convars.h]: This should be under `pf_`.

File: src/game/shared/tf/tf_weapon_passtime_gun.cpp [hunk 3]
```diff
@@ -552,15 +538,12 @@ void CPasstimeGun::ItemPostFrame()
...
 				// play the lock-on sound for the player
-				CRecipientFilter filter;
-				filter.AddRecipient( pOwner );
-				EmitSound( filter, pOwner->entindex(), kTargetHightlightSound );
-
-				// now play it for the target
-				filter.RemoveAllRecipients();
-				filter.AddRecipient( pCurrentTarget );
-				EmitSound( filter, pCurrentTarget->entindex(), kTargetHightlightSound );
+				pOwner->EmitSound( kTargetHightlightSound );
```
Comment (drunderscore) [inline src/game/shared/tf/tf_weapon_passtime_gun.cpp]: Emitting a sound is a side-effect, and needs to be protected with `prediction->IsFirstTimePredicted()` or similar to prevent the sound from being emitted multiple times if re-predicting (easily happens on some lag, test with `net_fakelag`)

File: src/game/shared/tf/tf_weapon_passtime_gun.cpp [hunk 4]
```diff
@@ -552,15 +538,12 @@ void CPasstimeGun::ItemPostFrame()
...
+				// play it for the target
+				pCurrentTarget->EmitSound( kTargetHightlightSound );
```
Comment (drunderscore) [inline src/game/shared/tf/tf_weapon_passtime_gun.cpp]: The original code was transcribed incorrectly here when swapping logical sides -- it doesn't make sense to play this sound on the carrier's client. This is causing _no sound_ to be heard when you are locked-on to.

**Review by drunderscore — DISMISSED** [review]
I'm sure you're aware of the consequences of this being made client-authoritative. A cheat client can lock-on without LOS even which is slightly silly but possibly not a realistic concern (I specifically tested this).

Additionally, you may find `snd_show 1` to help with resolving some of the comments about the sound.

I used `net_fakelag 45` and `net_fakejitter 15` on a listen server for testing (meaning 90 ping minimum).

**Comment by allvei** [comment]
Ignore this for now.

**Comment by allvei** [comment]
Tested with `net_fakelag 100` works good now, also no dupe sounds.
Not tested online.

File: src/game/shared/tf/passtime_convars.h [hunk 5]
```diff
@@ -92,8 +92,8 @@ extern ConVar
```
Comment (CarlJosell) [inline src/game/shared/tf/passtime_convars.h:93]: p4ss_passtime_lock_angle needs to be in the header file aswell.

**Review by CarlJosell — CHANGES_REQUESTED** [review]
It seems like the lock angle convar was never initialized in the header file. Fails on build.

File: src/game/shared/tf/passtime_convars.h (hunk 5 above)
Comment (allvei) [reply src/game/shared/tf/passtime_convars.h:93]: You can make the change

Comment (allvei) [reply src/game/shared/tf/passtime_convars.h:93]: Resolved in latest commit.

**Review by CarlJosell — COMMENTED** [review]
The actual issue is now fixed and works as intended. 

However there's an old issue with tf_hud_deathnotice where the function GetShortNick() doesn't return the correct type. Idk how this ended up here and why it's breaking now. 

Imo delete that piece of shit and get this PR in, and try to fix the shortname stuff for killfeed in another issue.

**Review by CarlJosell — APPROVED** [review]
