### PR TITLE
Fix trail colors, add more crosshairs + trails, add filtered mipmaps

### LINKED ISSUE #146: Add optional hud element to to indicate holding the jack
Viewmodels are not always preferred, but in pass time, it's often preferred to keep viewmodels on purely because it is easier to tell if you have the ball or not.
Perhaps we can introduce a hud element to give the players something back with this?

### LINKED ISSUE #150: For CVars using colours, introduce hex values to simplify colour selection process via console.

### PR DESCRIPTION
**Pull request by kindredtf**
## Asset changes/additions:
- **All ball crosshairs re-exported to new VTFs with BGRA8888 compression instead of DXT1/5**
  - Added filtered mipmaps to each crosshair VTF (prevents shimmering at distance)
    - Side effect: crosshairs will appear blurry at distance unless anisotropic filtering is on
    - I think this is the right tradeoff, as it is otherwise impossible to remove the "shimmering" from unfiltered high-res textures
  - Default ball crosshairs are still in the game as-is, unfiltered
- Added `p1fix` to complete the set: `plfix`, `p1fix`, `p2fix` (filtered versions of PT defaults)
- Added `pf` + `pfring` (PASS Fortress logo crosshair)
- Added custom trails (not changeable in game)
  - BLU trail color was noticeably different from its ball outline counterpart
    - Discussed in discord, changed the RED trail color to be slightly darker and RED ball outline slightly lighter
    - Teams' colors look more equivalent now
  - Remade trail assets: 64x64 filtered instead of 32x32
    - Default, default with outlines, flat color, flat color with outline
    - Remade default trail is active by default
- **Added some basic VTF crosshairs for use with `cl_crosshair_file`**
  - Assets are in /vgui/crosshair as this is where `cl_crosshair_file` already prepends to

## ConVar changes
- **Added a hud element to show when you are holding the ball**
  - `pf_ballindicator 1` to enable
  - `pf_ballindicator_file` (path)
  - `pf_ballindicator_scale` (float)
  - `pf_ballindicator_color` (R G B)
  - `pf_ballindicator_teamcolored` (1/0) overrides color

 - Changed color convars to use one RGB string
   - Removed `cl_crosshair_red/blue/green`
   - Removed `pf_crosshair_inner_r/g/b`
   - Removed `pf_crosshair_outer_r/g/b`
   - Added `cl_crosshair_color` (R G B)
   - Added `pf_crosshair_inner_color` (R G B)
   - Added `pf_crosshair_outer_color` (R G B)

 - Changed throw reticle teamcolored convar 
   - Now uses the same colors as the other teamcolored reticles
   - Simplified code
 

Closes #150 
Closes #146

### CODE REVIEW

File: src/game/shared/tf/tf_weaponbase.cpp [hunk 1]
```diff
@@ -262,7 +262,7 @@ END_DATADESC()
 // Client specific
 #else
 
-ConVar cl_crosshaircolor( "cl_crosshaircolor", "0", FCVAR_CLIENTDLL | FCVAR_ARCHIVE );
+//ConVar cl_crosshaircolor( "cl_crosshaircolor", "0", FCVAR_CLIENTDLL | FCVAR_ARCHIVE );
```
Comment (allvei) [inline src/game/shared/tf/tf_weaponbase.cpp:265]: Many console commands around crosshairs use snake case all throughout, so for consistency, I suggest using cl_crosshair_color instead of _crosshaircolor.
Similar should apply for other such ConVar's.

Otherwise all good.

**Comment by kindredtf** [comment]
changed the command name, also updated the PR description with a full description of commits

**Review by allvei — APPROVED** [review]
All good!
